### ISSUE TITLE
Cannot install in the latest Moodle 3.8.1+ (Build: 20200221)

### ISSUE THREAD

**Issue by raycheng0908** [vfremaux/moodle-local_vflibs#2]
When install this plugin in our moodle site (3.8.1+ Build: 20200221), the system return the message as below:

**Validating local_vflibs ... Error
  [Error] Required Moodle version [2019112200] 
Installation aborted due to validation failure**

**Comment by vfremaux** [comment]
Actually there has been a confusion in the moodle 3.8 core reference date : the good date is 2019111200.
You can change it in the version.php file.

Repo being fixed...

**Comment by raycheng0908** [comment]
It works, Thanks.
